language: node_js
node_js:
  - "0.10"

before_install:
  - npm install gulp -g

install:
  - npm install

before_script:

script:
  - gulp test

after_script:
  - cat tests/results/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  